version: "3.9"

services:
  # Production service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # host:container
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - NEXT_PUBLIC_PORT=3001
    restart: unless-stopped
    profiles:
      - prod

  # Development service with hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"  # host:container
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - NEXT_PUBLIC_PORT=3002
      # Point Next.js rewrites to the host's backend while running inside Docker
      - BACKEND_ORIGIN=http://host.docker.internal:1000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - POLLING_INTERVAL=1000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    profiles:
      - dev
