'use client';

import * as React from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Typography,
  Box,
  IconButton,
  Button,
  TextField,
  useTheme,
  Alert,
  CircularProgress,
} from '@mui/material';
import { XCircle as CloseIcon } from '@phosphor-icons/react/dist/ssr/XCircle';
import { Printer } from '@phosphor-icons/react/dist/ssr/Printer';
import { authClient } from '@/lib/auth/client';

interface PaymentDialogProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
  contraventionData: {
    id: string;
    shaftnumber: string;
    fineAmount: number;
    shaftId?: string;
  } | null;
}

export function PaymentDialog({ 
  open, 
  onClose, 
  onSuccess,
  contraventionData 
}: PaymentDialogProps): React.JSX.Element {
  const theme = useTheme();
  const [paymentAmount, setPaymentAmount] = React.useState<string>('');
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string>('');

  // Reset form when dialog opens/closes
  React.useEffect(() => {
    if (open && contraventionData) {
      setPaymentAmount(contraventionData.fineAmount.toString());
      setError('');
    } else {
      setPaymentAmount('');
      setError('');
    }
  }, [open, contraventionData]);

  const handleAmountChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value;
    // Allow only numbers and decimal point
    if (value === '' || /^\d*\.?\d*$/.test(value)) {
      setPaymentAmount(value);
      setError('');
    }
  };

  const handleSubmit = async () => {
    if (!contraventionData) return;

    const amount = parseFloat(paymentAmount);
    
    // Validation
    if (isNaN(amount) || amount <= 0) {
      setError('Please enter a valid amount');
      return;
    }

    if (amount < contraventionData.fineAmount) {
      setError(`Amount cannot be less than the required fine amount of $${contraventionData.fineAmount.toLocaleString()}`);
      return;
    }

    setLoading(true);
    setError('');

    try {
      // First, mark the fine as paid
      const paymentResult = await authClient.markFinePaid(contraventionData.id, amount);
      
      if (!paymentResult.success) {
        throw new Error(paymentResult.error || 'Failed to process payment');
      }

      // If payment is successful and we have a shaft ID, suspend the shaft
      if (contraventionData.shaftId) {
        const suspendResult = await authClient.suspendShaftForSHE(contraventionData.shaftId, 'APPROVED');
        
        if (!suspendResult.success) {
          // Payment succeeded but suspension failed - log warning but don't fail the whole operation
          console.warn('Payment processed but shaft suspension failed:', suspendResult.error);
        }
      }

      // Success - trigger table refresh
      onSuccess();
      onClose();
    } catch (error) {
      console.error('Payment processing error:', error);
      setError(error instanceof Error ? error.message : 'An error occurred while processing the payment');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    const printContent = `
      <div style="font-family: Arial, sans-serif; padding: 20px;">
        <h2 style="color: #1976d2; margin-bottom: 20px;">Payment Receipt</h2>
        <div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
          <h3 style="margin: 0 0 15px 0; color: #333;">Payment Details</h3>
          <p><strong>Shaft Number:</strong> ${contraventionData?.shaftnumber}</p>
          <p><strong>Required Fine Amount:</strong> $${contraventionData?.fineAmount.toLocaleString()}</p>
          <p><strong>Payment Amount:</strong> $${parseFloat(paymentAmount || '0').toLocaleString()}</p>
          <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          <p><strong>Time:</strong> ${new Date().toLocaleTimeString()}</p>
        </div>
        <div style="border-top: 2px solid #1976d2; padding-top: 15px;">
          <p style="font-size: 12px; color: #666;">Generated by Co-app System</p>
        </div>
      </div>
    `;
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.print();
      printWindow.close();
    }
  };

  if (!contraventionData) return <></>;

  const minAmount = contraventionData.fineAmount;
  const currentAmount = parseFloat(paymentAmount) || 0;
  const isValidAmount = currentAmount >= minAmount && currentAmount > 0;

  return (
    <Dialog 
      open={open} 
      onClose={onClose}
      maxWidth="sm"
      fullWidth
      PaperProps={{
        sx: { 
          borderRadius: 3,
          maxHeight: '90vh'
        }
      }}
    >
      <DialogTitle sx={{ 
        display: 'flex', 
        justifyContent: 'space-between', 
        alignItems: 'center',
        background: `linear-gradient(135deg, ${theme.palette.secondary.main} 0%, ${theme.palette.secondary.dark} 100%)`,
        color: 'white',
        py: 2.5,
        px: 3,
        m: 0,
        fontWeight: 600
      }}>
        Process Payment
        <Box sx={{ display: 'flex', gap: 1 }}>
          <IconButton
            onClick={handlePrint}
            size="small"
            sx={{ color: 'white' }}
            disabled={loading || !isValidAmount}
          >
            <Printer />
          </IconButton>
          <IconButton
            onClick={onClose}
            size="small"
            sx={{ color: 'white' }}
            disabled={loading}
          >
            <CloseIcon />
          </IconButton>
        </Box>
      </DialogTitle>

      <DialogContent sx={{ p: 3 }}>
        {/* Contravention Details */}
        <Box sx={{ 
          border: `2px solid ${theme.palette.secondary.main}`, 
          borderRadius: '12px', 
          p: 2.5,
          mb: 3,
          bgcolor: '#ffffff'
        }}>
          <Typography 
            variant="subtitle1" 
            sx={{ 
              color: theme.palette.secondary.main, 
              fontWeight: 700, 
              mb: 2,
              fontSize: '1rem',
              textTransform: 'uppercase',
              letterSpacing: '0.5px'
            }}
          >
            Payment Details
          </Typography>
          
          <Box sx={{ mb: 2 }}>
            <Typography variant="body2" color="text.secondary" gutterBottom>
              Shaft Number
            </Typography>
            <Typography variant="body1" fontWeight={600}>
              {contraventionData.shaftnumber}
            </Typography>
          </Box>

          <Box sx={{ mb: 2 }}>
            <Typography variant="body2" color="text.secondary" gutterBottom>
              Required Fine Amount
            </Typography>
            <Typography variant="h6" color="error.main" fontWeight={700}>
              ${contraventionData.fineAmount.toLocaleString()}
            </Typography>
          </Box>
        </Box>

        {/* Payment Amount Input */}
        <Box sx={{ mb: 3 }}>
          <TextField
            fullWidth
            label="Payment Amount"
            value={paymentAmount}
            onChange={handleAmountChange}
            placeholder="Enter payment amount"
            disabled={loading}
            error={!!error || (currentAmount > 0 && !isValidAmount)}
            helperText={
              error || 
              (currentAmount > 0 && !isValidAmount 
                ? `Amount must be at least $${minAmount.toLocaleString()}` 
                : `Minimum amount: $${minAmount.toLocaleString()}`
              )
            }
            InputProps={{
              startAdornment: (
                <Typography variant="body1" sx={{ mr: 1, color: 'text.secondary' }}>
                  $
                </Typography>
              ),
            }}
            sx={{
              '& .MuiOutlinedInput-root': {
                '&.Mui-focused fieldset': {
                  borderColor: theme.palette.secondary.main,
                },
              },
            }}
          />
        </Box>

        {/* Payment Summary */}
        {isValidAmount && (
          <Box sx={{ 
            bgcolor: theme.palette.success.main + '10', 
            border: `1px solid ${theme.palette.success.main}40`,
            borderRadius: 2, 
            p: 2, 
            mb: 2 
          }}>
            <Typography variant="subtitle2" color="success.main" gutterBottom>
              Payment Summary
            </Typography>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
              <Typography variant="body2">Fine Amount:</Typography>
              <Typography variant="body2" fontWeight={600}>
                ${contraventionData.fineAmount.toLocaleString()}
              </Typography>
            </Box>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
              <Typography variant="body2">Payment Amount:</Typography>
              <Typography variant="body2" fontWeight={600}>
                ${currentAmount.toLocaleString()}
              </Typography>
            </Box>
            {currentAmount > contraventionData.fineAmount && (
              <Box sx={{ display: 'flex', justifyContent: 'space-between', pt: 1, borderTop: '1px solid #e0e0e0' }}>
                <Typography variant="body2" color="success.main">Overpayment:</Typography>
                <Typography variant="body2" fontWeight={600} color="success.main">
                  ${(currentAmount - contraventionData.fineAmount).toLocaleString()}
                </Typography>
              </Box>
            )}
          </Box>
        )}

        {/* Error Alert */}
        {error && (
          <Alert severity="error" sx={{ mb: 2 }}>
            {error}
          </Alert>
        )}
      </DialogContent>

      <DialogActions sx={{ 
        px: 3, 
        py: 2, 
        background: '#fafafa', 
        borderTop: '1px solid #eaeaea' 
      }}>
        <Button 
          onClick={onClose}
          variant="outlined"
          disabled={loading}
          sx={{ 
            borderColor: theme.palette.secondary.main,
            color: theme.palette.secondary.main,
            '&:hover': {
              borderColor: theme.palette.secondary.dark,
              bgcolor: 'rgba(50, 56, 62, 0.04)'
            }
          }}
        >
          Cancel
        </Button>
        <Button 
          onClick={handleSubmit}
          variant="contained"
          disabled={loading || !isValidAmount}
          startIcon={loading ? <CircularProgress size={16} color="inherit" /> : null}
          sx={{ 
            bgcolor: theme.palette.secondary.main,
            '&:hover': {
              bgcolor: theme.palette.secondary.dark,
            },
            '&:disabled': {
              bgcolor: theme.palette.grey[300],
            }
          }}
        >
          {loading ? 'Processing...' : 'Process Payment'}
        </Button>
      </DialogActions>
    </Dialog>
  );
}