export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
   dashboard: {
    overview: '/dashboard',
    Ore_reports: '/dashboard/ore_reports',
    shaftinspectionresolution: '/dashboard/shaftinspectionresolution',
    shaftcreation: '/dashboard/shaftcreation',
    shafttransfare: '/dashboard/shafttransfare',
    safetycheck: '/dashboard/safetycheck',
    Section_reports: '/dashboard/section_reports',
shafthistoryreports: '/dashboard/shafthistoryreports',
    map: '/dashboard/map',
    Penality_Payment: '/dashboard/penalitypayment',
    shaftinspection: '/dashboard/shaftinspection',
    listissuedpenality: '/dashboard/listissuedpenality',
    training: '/dashboard/training',
    guilty: '/dashboard/guilty',
    resolveissue: '/dashboard/resolveissue',
    account: '/dashboard/account',
    penality:'/dashboard/penality',
    sectionmapping: '/dashboard/sectionmapping',
    customers: '/dashboard/customers',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
    incidentmanagement: '/dashboard/incidentmanagement',
    useronboard: '/dashboard/useronboard',
    Syndicate: '/dashboard/syndicate',
    shaftreg: '/dashboard/shaftassign',
    Transport_cost: '/dashboard/Transport_cost',
    ShaftLoanStatus: '/dashboard/ShaftLoanStatus',
    Sample_Ore_Approval:'/dashboard/Sample_Ore_Approval',
    Production_loan:'/dashboard/Production_Loan',
    oreTax: '/dashboard/oretax',
    mill: '/dashboard/mill',
    borrowing:'/dashboard/borrowing',
    Transport_costStatus:'/dashboard/Transport_costStatus',
    Refined_Ore_to_Gold:'/dashboard/Refined_Ore_to_Gold',
    Production_LoanStatus:'/dashboard/Production_LoanStatus',
    millasignment:'/dashboard/millasignment',
    millstatus: '/dashboard/millstatus',
    Ore_Dispatch: '/dashboard/Ore_Dispatch',
    Ore_Recieval: '/dashboard/Ore_Recieval',
    Patrol_Log: '/dashboard/Patrol_Log',
    Incident_Report: '/dashboard/Incident_Report',
    securityonboarding: '/dashboard/securityonboarding',
    taxonboardingstatus: '/dashboard/taxonboardingstatus',
    sectioncreation: '/dashboard/sectioncreation',
    sectioncreationstatus: '/dashboard/sectioncreationstatus',
    minerDetails: '/dashboard/miner-details',
    oremanagement: '/dashboard/oremanagement',
    taxonboarding: '/dashboard/taxonboarding',
oreTransport: '/dashboard/oreTransport',
approvedvehic: '/dashboard/approvedvehicles',
    securityonboardingstatus: '/dashboard/securityonboardingstatus',
    driveronboarding: '/dashboard/driveronboarding',
    vehicleonboarding: '/dashboard/vehicleonboarding',
    vehicleonboardingstatus: '/dashboard/vehicleonboardingstatus',
    driveronboardingstatus: '/dashboard/driveronboardingstatus',
    useronboardstatus: '/dashboard/useronboardstatus',
    shaftassignmentstatus: '/dashboard/shaftassignmentstatus',
    incidentreports: '/dashboard/incidentreports',
    penaltyreports: '/dashboard/penaltyreports',
    trainingreports: '/dashboard/trainingreports',
    inspectionreports: '/dashboard/inspectionreports',
    shesummaryreports: '/dashboard/shesummaryreports',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
