export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    customers: '/dashboard/customers',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
    useronboard: '/dashboard/useronboard',
    Syndicate: '/dashboard/syndicate',
    shaftreg: '/dashboard/shaftassign',
    securityonboarding: '/dashboard/securityonboarding',
    sectioncreation: '/dashboard/sectioncreation',
    sectioncreationstatus: '/dashboard/sectioncreationstatus',
    minerDetails: '/dashboard/miner-details',
    oreManagement: '/dashboard/ore-management',
    securityonboardingstatus: '/dashboard/securityonboardingstatus',
    driveronboarding: '/dashboard/driveronboarding',
    driveronboardingstatus: '/dashboard/driveronboardingstatus',
    useronboardstatus: '/dashboard/useronboardstatus',
    shaftassignmentstatus: '/dashboard/shaftassignmentstatus',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
